### PR TITLE
Add save ministry EP

### PR DESCRIPTION
**Pull request by felipeeflores**
Adding endpoint to save a ministry (in memory only).

Details:
- completed E2E endpoint with a in memory storage (Routes - Controller - Service, no repository yet)
-  used `Optional` instead of `null` everywhere 🎉 🥳 
- added a `Runtime` component where "DI" occurs at compile time 🎉 ✌️ 
- all tests.
- remove hello world code from main class (`Muster.kt`). Pushed it to all to its own `HelloWorld` classes.
- started to define a theoretical hierarchy or packages to group code by endpoint.
- start with endpoint versioning from inception.
- make the app run indefinitely, use port 8888.
- added some minimal documentation 💝 

part of #2

### CODE REVIEW

**Comment by felipeeflores** [comment]
[Manage Ministries End Points](https://trello.com/c/nyFaBeDp/19-manage-ministries-end-points)

**Comment by rlaraujo** [comment]
Just a small detail: In a commit I read the port 8080 was going to be used, and 8888 is the one being used in the code

**Review by rlaraujo — COMMENTED** [review]
All good

**Comment by rlaraujo** [comment]
Reopening to be able to merge

**Review by rlaraujo — APPROVED** [review]

**Pull request merged**
